machines:
  - hostname: "dev" # hostname for dev machine
    port: "7122"
  - hostname: "fa23-cs425-8701.cs.illinois.edu"
    port: "7122"
  - hostname: "fa23-cs425-8702.cs.illinois.edu"
    port: "7122"
  - hostname: "fa23-cs425-8703.cs.illinois.edu"
    port: "7122"
  - hostname: "fa23-cs425-8704.cs.illinois.edu"
    port: "7122"
  - hostname: "fa23-cs425-8705.cs.illinois.edu"
    port: "7122"
  - hostname: "fa23-cs425-8706.cs.illinois.edu"
    port: "7122"
  - hostname: "fa23-cs425-8707.cs.illinois.edu"
    port: "7122"
  - hostname: "fa23-cs425-8708.cs.illinois.edu"
    port: "7122"
  - hostname: "fa23-cs425-8709.cs.illinois.edu"
    port: "7122"
  - hostname: "fa23-cs425-8710.cs.illinois.edu"
    port: "7122"
